# Generated by Django 5.0.2 on 2024-04-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail_form", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="file",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
