# Generated by Django 5.0.2 on 2024-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail_form", "0002_mail_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="file",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="address",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
